// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xzabikiuauxdbvncudsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6YWJpa2l1YXV4ZGJ2bmN1ZHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzODMyNzIsImV4cCI6MjA5MTk1OTI3Mn0.UnOD-oZ9mV_RIeLAG40vfsDOisos5EFqK-8rZ1wDnRc";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true, // 세션을 로컬 스토리지에 저장하여 유지
    autoRefreshToken: true, // 토큰 만료 전 자동으로 갱신
    detectSessionInUrl: true // 이메일 링크 등을 통한 로그인 감지
  }
});