// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xzabikiuauxdbvncudsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6YWJpa2l1YXV4ZGJ2bmN1ZHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzODMyNzIsImV4cCI6MjA5MTk1OTI3Mn0.UnOD-oZ9mV_RIeLAG40vfsDOisos5EFqK-8rZ1wDnRc";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'chora-auth-token', // 명시적인 스토리지 키 사용
  }
});